export const CAR_COLORS = [
    { value: "white", hex: "#FFFFFF", border: true },
    { value: "black", hex: "#000000", border: false },
    { value: "gray", hex: "#808080", border: false },
    { value: "silver", hex: "#C0C0C0", border: false },
    { value: "red", hex: "#EF4444", border: false },
    { value: "blue", hex: "#3B82F6", border: false },
    { value: "brown", hex: "#A52A2A", border: false },
    { value: "beige", hex: "#F5F5DC", border: true },
    { value: "green", hex: "#22C55E", border: false },
    { value: "gold", hex: "#DEB735", border: false },
    { value: "yellow", hex: "#EAB308", border: false },
    { value: "orange", hex: "#F97316", border: false },
    { value: "purple", hex: "#A855F7", border: false },
    { value: "bronze", hex: "#CD7F32", border: false },
    { value: "burgundy", hex: "#800020", border: false },
    { value: "champagne", hex: "#F7E7CE", border: true },
    { value: "teal", hex: "#14B8A6", border: false },
    { value: "metallic", hex: "linear-gradient(135deg, #E0E0E0 0%, #9ca3af 100%)", border: false },
    { value: "matte_black", hex: "#1C1C1C", border: false },
    { value: "other", hex: "conic-gradient(from 180deg at 50% 50%, #FF0000 0deg, #00FF00 120deg, #0000FF 240deg, #FF0000 360deg)", border: false },
] as const;
