// Central runtime config — DO NOT edit this file for deployment.
// Use .env.local (or your host's environment variables) as the single place to change settings.

type HeaderLike = { get: (name: string) => string | null }

export const runtimeConfig = {
  // Do NOT hardcode production values here. Set NEXT_PUBLIC_SITE_URL in .env.local on the server.
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL ?? "",

  // DB defaults read from environment. To change DB credentials in production edit .env.local only.
  db: {
    host: process.env.DB_HOST ?? "localhost",
    port: Number(process.env.DB_PORT ?? 3306),
    user: process.env.DB_USER ?? "root",
    password: process.env.DB_PASSWORD ?? "",
    name: process.env.DB_NAME ?? "karkey",
  },
}

/**
 * Get canonical base URL to use for server-side absolute fetches.
 * Priority:
 * 1) NEXT_PUBLIC_SITE_URL from env (recommended)
 * 2) headers x-forwarded-host / host + x-forwarded-proto
 * 3) fallback to http://localhost:3000
 */
export function getSiteBaseUrl(hdrs?: HeaderLike | null) {
  if (runtimeConfig.siteUrl && runtimeConfig.siteUrl.trim() !== "") {
    return runtimeConfig.siteUrl.replace(/\/+$/, "")
  }

  try {
    const host = hdrs?.get?.("x-forwarded-host") ?? hdrs?.get?.("host") ?? null
    const proto = hdrs?.get?.("x-forwarded-proto") ?? "http"
    if (host) return `${proto}://${host}`
  } catch {
    // ignore
  }

  return "http://localhost:3000"
}
